server:
  port: 8090
logging:
  level:
    com:
      wb: debug
mybatis:
  type-aliases-package: com.wb.pojo
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mf
    password: 996649855
    username: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
