spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    druid:
      url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=false
      password: 996649855
    driver-class-name: org.gjt.mm.mysql.Driver
mybatis:
#  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.wb.pojo
server:
  port: 80
logging:
  level:
    com:
      wb:
       dao: debug




